import streamlit as st

 # when we name two buttons with the same name, it throws an error because
# streamlit does not know which button to refer to because it gives every button 
# an autogenerated ID
# so we need to give them unique names 

st.button('OK')
st.button('OK', key='btn2')
st.divider()
if 'slider' not in st.session_state:
    st.session_state.slider = 20

min_value = st.slider("Set Min value ",0, 100, 10)
st.session_state.slider = st.slider("Slider 2", min_value, 100, st.session_state.slider)

